sudo: 'required'

git:
  depth: 3

branches:
  only:
  - master

language: python
python:
  - "2.7"

services:
  - 'docker'

script:
  - 'make build'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make publish ;
    fi
